name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    permissions: write-all
    name: Autograding
    runs-on: self-hosted
    steps:
      - name: Check-in Student Repo
        uses: actions/checkout@v2
      
      - name: Check-in Clean Test Collateral
        uses: actions/checkout@v2
        with:
          repository: CSCE313-SU22-Tyagi/public-tests
          path: tests
      
      - name: Set-up Autograder Environment
        run: |
          mkdir .github/classroom/
          cp tests/graders/grading_le5.json .github/classroom/autograding.json
          cp tests/makefiles/makefile_le5 makefile
          cp -r tests/collateral/le5-tests/ test-files/
      - name: Run Autograder
        uses: education/autograding@v1